import React from "react";
import type { Metadata } from "next";

import "@/styles/global.scss";

import { NavMain } from "@/components/NavMain";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "In The Dark Circus Arts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavMain />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
